version: "3.7"
services:
  #############
  ## SERVER ##
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - webapp
      - database
    depends_on:
      - postgres_db
    env_file:
      - ./server/.env
    restart: always
    command:
      ["./wait-for-it.sh", "postgres_db:5432", "--", "node", "./src/main.js"]
    container_name: server
  #############
  ## CLIENT ##
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    networks:
      - webapp
    ports:
      - 8000:8000
    restart: always
    container_name: client
  ##############
  ## POSTGRES ##
  postgres_db:
    image: postgres
    networks:
      - database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hangman
    volumes:
      - ./server/database/data/prod:/var/lib/postgresql/data/
    restart: always
    container_name: postgres_db
networks:
  webapp:
    driver: bridge
  database:
    driver: bridge
